### ISSUE TITLE
Microsoft.WindowsFabric.*.dll files are referenced when package is installed.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Grimace1975/bclcontrib-abstract#1] opened 2015-04-19 17:20 UTC
```
What steps will reproduce the problem?
1. Install ServerAppFabric.Client through NuGet Manager in Visual Studio 2012 
to a project.
2. Observe that only the 2 Microsoft.ApplicationServer.Caching.*.dll files get 
added to the project references.

What is the expected output? What do you see instead?
- All 4 DLL files in the package should be referenced.

What version of the product are you using? On what operating system?
- 1.1.216

Please provide any additional information below.
- Solution: Remove the <references /> tag from the .nuspec file.
```

Original issue reported on code.google.com by `anton.ge...@gmail.com` on 22 May 2013 at 3:04

**Comment by Grimace1975** [comment] 2017-05-07 16:29
This was the intended behavior. Only the referenced dlls are required for most cases. Closing issue

**Closed** 2017-05-07 16:28 UTC
Labels: auto-migrated, Priority-Medium, Type-Defect
